process:
  process_name: "Incident Management"
  process_description: "Incident Management process for IT service desk"
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  num_cases: 1000
  traces:
    - "(report,assign,resolve,close)^300"
    - "(report,assign,escalate,resolve,close)^200"
    - "(report,resolve,close)^150"
    - "(report,close)^100"
    - "(report,assign,resolve)^250"
  case_attributes:
    - name: "IncidentID"
      type: "UUID"
      distribution: "uniform"
    - name: "Priority"
      type: "Categorical"
      categories: ["Low", "Medium", "High", "Critical"]
      distribution: "uniform"
    - name: "ReportedBy"
      type: "Resource"
      resource_type: "human"
      distribution: "normal"
      range: "1..100"
  activities:
    - name: "Incident Reported"
      trace: "report"
      order: 1
      min_weight: 1
      max_weight: 2
      distribution: "uniform"
      transaction_types:
        - name: "start"
          order: 1
        - name: "complete"
          order: 2
      activity_attributes:
        - name: "ReportedBy"
          type: "Resource"
          resource_type: "human"
          distribution: "normal"
          range: "1..100"
    - name: "Incident Assigned"
      trace: "assign"
      order: 2
      min_weight: 1
      max_weight: 2
      distribution: "uniform"
      transaction_types:
        - name: "start"
          order: 2
        - name: "complete"
          order: 3
      activity_attributes:
        - name: "AssignedTo"
          type: "Resource"
          resource_type: "human"
          distribution: "normal"
          range: "1..50"
    - name: "Incident Resolved"
      trace: "resolve"
      order: 3
      min_weight: 1
      max_weight: 2
      distribution: "uniform"
      transaction_types:
        - name: "start"
          order: 3
        - name: "complete"
          order: 4
      activity_attributes:
        - name: "ResolvedBy"
          type: "Resource"
          resource_type: "human"
          distribution: "normal"
          range: "1..50"
    - name: "Incident Closed"
      trace: "close"
      order: 4
      min_weight: 1
      max_weight: 3
      distribution: "normal"
      transaction_types:
        - name: "start"
          order: 4
        - name: "complete"
          order: 5
      activity_attributes:
        - name: "ClosedBy"
          type: "Resource"
          resource_type: "human"
          distribution: "normal"
          range: "1..50"
    - name: "Incident Escalated"
      trace: "escalate"
      order: 3
      min_weight: 1
      max_weight: 2
      distribution: "uniform"
      transaction_types:
        - name: "start"
          order: 3
        - name: "complete"
          order: 4
      activity_attributes:
        - name: "EscalatedBy"
          type: "Resource"
          resource_type: "human"
          distribution: "normal"
          range: "1..30"
  event_attributes:
    - name: "Location"
      type: "Character"
      distribution: "uniform"
      generation_level: "event"
    - name: "Duration"
      type: "Numeric"
      distribution: "normal"
      range: "1..10"
      generation_level: "event"
    - name: "Timestamp"
      type: "Datetime"
      distribution: "uniform"
      generation_level: "event"
  object_types:
    - name: "Incident"
      range: "1..4"
      object_attributes:
        - name: "IncidentType"
          type: "Categorical"
          categories: [ "Hardware", "Software", "Network", "Security" ]
          distribution: "uniform"
        - name: "Impact"
          type: "Categorical"
          categories: [ "Low", "Medium", "High", "Critical" ]
          distribution: "uniform"
      activity_qualifiers:
        - name: "Incident Created"
          to_activity: "Incident Reported"
        - name: "Incident Closed"
          to_activity: "Incident Closed"
      object_qualifiers:
        - name: "assigned to"
          to_object: "Person"
    - name: "Person"
      range: "1..4"
      object_attributes:
        - name: "Role"
          type: "Categorical"
          categories: [ "Reporter", "Assignee", "Resolver", "Escalator", "Closer" ]
          distribution: "uniform"